### ISSUE TITLE
RunOrchestrator called multiple times

### ISSUE THREAD

**Issue by alexjamesbrown** [Azure-Samples/durablefunctions-apiscraping-dotnet#1]
When running this, if I put a breakpoint in the RunOrchestrator method, I see that it's hit multiple times...

Is that because of this?
https://github.com/Azure/azure-functions-durable-extension/issues/612

Or something else?

**Comment by MaximRouiller** [comment]
It's definitely a possibility.

Is it starting multiple Orchestration with multiple IDs or is it the same one resuming? Orchestrator function can (and will) restart multiple times.

**Comment by alexjamesbrown** [comment]
my bad, it was the Orchestrator function (as expected)
