### ISSUE TITLE
Location of local.settings.json?

### ISSUE THREAD

**Issue by tjl694** [Azure-Samples/durablefunctions-apiscraping-dotnet#5]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>Read the docs

### Expected/desired behavior
>Docs contain the desired location for local.settings.json file

**Comment by pieronegri** [comment]
to me it looks like the whole function app project is missing. As far as I can see only a class library is provided: "FanOutFanInCrawler". This would explain why the local settings is missing as well as you can not publish the app.
